---
abstract: 'work with nestable Pod elements'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires:
  Data::Dumper: 0
  Test::Deep: 0
  Test::Differences: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Elemental
requires:
  Encode: 0
  Mixin::Linewise::Readers: 0
  Moose: 0
  Moose::Autobox: 0.10
  Moose::Role: 0.90
  Moose::Util::TypeConstraints: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Pod::Eventual::Simple: 0.004
  String::RewritePrefix: 0
  String::Truncate: 0
  Sub::Exporter: 0
  Sub::Exporter::ForMethods: 0
  Test::Deep: 0
  Test::Differences: 0
  namespace::autoclean: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  homepage: https://github.com/rjbs/pod-elemental
  repository: https://github.com/rjbs/pod-elemental.git
version: 0.102362
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@RJBS/Git::GatherDir'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@RJBS/CheckPrereqsIndexed'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@RJBS/CheckExtraTests'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RJBS/@Filter/PruneCruft'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@RJBS/@Filter/ManifestSkip'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RJBS/@Filter/MetaYAML'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::License
      name: '@RJBS/@Filter/License'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@RJBS/@Filter/Readme'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RJBS/@Filter/ExecDir'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RJBS/@Filter/ShareDir'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RJBS/@Filter/MakeMaker'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RJBS/@Filter/Manifest'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RJBS/@Filter/TestRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RJBS/@Filter/ConfirmRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RJBS/@Filter/UploadToCPAN'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RJBS/AutoPrereqs'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@RJBS/Git::NextVersion'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@RJBS/PkgVersion'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RJBS/MetaConfig'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RJBS/MetaJSON'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RJBS/NextRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RJBS/PodSyntaxTests'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@RJBS/TestMoreWithSubtests'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@RJBS/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@RJBS/GithubMeta'
      version: 0.28
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RJBS/@Git/Check'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RJBS/@Git/Commit'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RJBS/@Git/Tag'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RJBS/@Git/Push'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereq
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300015
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300015
